name: Build RK322x U-Boot and Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git build-essential bc libncurses5-dev debootstrap \
          qemu-user-static dosfstools gparted rsync unzip parted pv \
          curl gcc-aarch64-linux-gnu device-tree-compiler \
          python3-dev python3-pip python3-venv \
          libssl-dev liblz4-tool zlib1g-dev \
          flex bison libelf-dev dwarves
        
        # Install additional Python dependencies
        pip3 install --user pyyaml
        
    - name: Build Armbian for RK322x
      run: |
        # Start the build process directly
        ./compile.sh \
          BOARD=rk322x-box \
          BRANCH=current \
          RELEASE=jammy \
          BUILD_MINIMAL=no \
          BUILD_DESKTOP=no \
          KERNEL_ONLY=yes \
          KERNEL_CONFIGURE=no
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rk322x-build-artifacts
        path: |
          output/debs/
          output/images/
        if-no-files-found: error
        retention-days: 5
