name: Build Armbian for RK322x

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git build-essential bc binutils bison flex \
          libssl-dev libncurses5-dev \
          parted debootstrap debian-archive-keyring \
          qemu-user-static dosfstools
    
    - name: Build Armbian
      run: |
        # Set non-interactive environment
        export DEBIAN_FRONTEND=noninteractive
        export BUILD_OPTIONS="noconfig"
        export FORCE_BOOTSCRIPT_UPDATE="no"
        export SHOW_DEBUG=yes
        
        # Fix potential line endings
        find . -type f -name "*.sh" -exec sed -i 's/\r$//' {} \;
        
        # Build kernel
        ./compile.sh \
          BOARD=rk322x-box \
          BRANCH=current \
          KERNEL_CONFIGURE=no \
          LOG_SUBPATH="github-actions" \
          kernel 2>&1 | tee kernel-build.log
        
        # Build U-Boot
        ./compile.sh \
          BOARD=rk322x-box \
          BRANCH=current \
          u-boot 2>&1 | tee u-boot-build.log
        
        # Generate boot.scr
        echo -e 'setenv bootargs "console=ttyS2,115200n8 root=PARTUUID=${uuid} rw rootwait"\nload mmc 0:1 ${kernel_addr_r} /boot/zImage\nload mmc 0:1 ${fdt_addr_r} /boot/dtb/${fdtfile}\nbootz ${kernel_addr_r} - ${fdt_addr_r}' > boot.cmd
        mkimage -C none -A arm -T script -d boot.cmd boot.scr
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armbian-build
        path: |
          output/images/*
          *.log
          boot.scr
        retention-days: 3
