name: Build RK322x Kernel and U-Boot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git build-essential bc libncurses5-dev debootstrap \
          qemu-user-static dosfstools gparted rsync unzip parted pv \
          curl gcc-aarch64-linux-gnu device-tree-compiler \
          python3-dev python3-pip python3-venv \
          libssl-dev liblz4-tool zlib1g-dev \
          flex bison libelf-dev dwarves
        
        pip3 install --user pyyaml
        
    - name: Build for RK322x
      run: |
        # Force non-interactive mode for all configuration
        export DEBIAN_FRONTEND=noninteractive
        export BUILD_MINIMAL=no
        export BUILD_DESKTOP=no
        export KERNEL_CONFIGURE=no
        export BSP_BUILD_ONLY=yes
        export MINIMAL_IMAGE=no
        export NO_HOST_RELEASE_CHECK=yes
        export SKIP_EXTERNAL_TOOLCHAINS=yes
        
        # Run build with all interactive options disabled
        ./compile.sh \
          BOARD=rk322x-box \
          BRANCH=current \
          RELEASE=jammy \
          CLEAN_LEVEL="make,debs" \
          LOG_SUBPATH="github-actions" 2>&1 | tee build.log
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rk322x-build-artifacts
        path: |
          output/debs/linux-*
          output/debs/u-boot-*
          output/images/u-boot-*
          build.log
        if-no-files-found: error
        retention-days: 5
