name: Download boot.scr for RK322x

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  download-boot-scr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download boot.scr
      run: |
        # Download boot.scr from CodeBoomAI repository
        wget https://github.com/CodeBoomAI/armbian-build-rk322x/raw/main/output/images/boot.scr
        
        # Verify downloaded file
        if [ ! -f "boot.scr" ]; then
          echo "Error: boot.scr not downloaded!"
          exit 1
        fi
        
        # Check file size to ensure proper download
        file_size=$(stat -c%s "boot.scr")
        if [ "$file_size" -lt 1024 ]; then
          echo "Error: Downloaded file seems too small (only $file_size bytes)"
          exit 1
        fi
        
        echo "File boot.scr downloaded successfully:"
        ls -lh boot.scr
        file boot.scr
        
    - name: Upload boot.scr as artifact
      uses: actions/upload-artifact@v4
      with:
        name: boot-scr-file
        path: boot.scr
        retention-days: 5
