name: Generate boot.scr for RK322x

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate-boot-scr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y u-boot-tools
        
    - name: Create boot.cmd
      run: |
        cat << 'EOF' > boot.cmd
        # Boot script for RK322x
        setenv bootargs "earlyprintk console=ttyS2,115200n8 console=tty1 root=PARTUUID=${uuid} rw rootwait rootfstype=ext4"
        load mmc 0:1 ${kernel_addr_r} /boot/zImage
        load mmc 0:1 ${fdt_addr_r} /boot/dtb/${fdtfile}
        bootz ${kernel_addr_r} - ${fdt_addr_r}
        EOF
        
    - name: Generate boot.scr
      run: |
        mkdir -p output/images
        mkimage -C none -A arm -T script -d boot.cmd output/images/boot.scr
        
    - name: Verify file
      run: |
        if [ ! -s "output/images/boot.scr" ]; then
          echo "Error: boot.scr is empty or missing!"
          exit 1
        fi
        echo "File generated successfully:"
        ls -lh output/images/boot.scr
        file output/images/boot.scr
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: boot-files
        path: output/images/boot.scr
