name: Download boot files for RK322x

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  download-boot-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download boot files
      run: |
        # Create directory structure
        mkdir -p output/images
        
        # Try multiple possible locations for boot.scr
        possible_paths=(
          "https://github.com/CodeBoomAI/armbian-build-rk322x/raw/main/boot.scr"
          "https://github.com/CodeBoomAI/armbian-build-rk322x/raw/main/images/boot.scr"
          "https://github.com/CodeBoomAI/armbian-build-rk322x/raw/main/output/boot.scr"
        )
        
        for url in "${possible_paths[@]}"; do
          echo "Trying to download from: $url"
          if wget "$url" -O output/images/boot.scr; then
            echo "Successfully downloaded boot.scr"
            break
          fi
        done
        
        # Verify downloaded file
        if [ ! -f "output/images/boot.scr" ]; then
          echo "Error: Could not find boot.scr in any known location"
          exit 1
        fi
        
        echo "File downloaded successfully:"
        ls -lh output/images/boot.scr
        file output/images/boot.scr
        
    - name: Upload boot files
      uses: actions/upload-artifact@v4
      with:
        name: boot-files
        path: output/images/boot.scr
        retention-days: 5
